before:
  hooks:
    - go mod download
build:
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
brew:
  github:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
dockers:
  - image: caarlos0/github_releases_exporter
    extra_files:
    - releases.yml
    tag_templates:
    - latest
    - "{{ .Tag }}"
    - "v{{ .Major }}"
